name: RunForMoney
version: '${project.version}'
main: snw.rfm.RunForMoney
api-version: 1.16
author: "SNWCreations"
description: '${project.description}'
website: https://github.com/SNWCreations/RunForMoney
depend: [CommandAPI]

# Commands
commands:
  start:
    description: "开始 '全员逃走中' 游戏。当提供 countDownTime 参数时，用提供的值作为猎人的释放时间。如果没有提供值或提供的值为负值，则使用配置文件提供的值。"
    usage: "/start [countDownTime: int]"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.start"
  pause:
    description: "暂停游戏。"
    usage: "/pause"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.pause"
  resume:
    description: "继续游戏进程。一般在所有游戏玩家掉线但都成功重连后使用。"
    usage: "/resume"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.resume"
  forcestop:
    description: "强制停止 '全员逃走中' 游戏。"
    usage: "/forcestop"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.forcestop"
  hunter:
    description: "成为猎人。当 playername 参数存在时，则强制让 <playername> 玩家成为猎人。playername 可以为多个，例如 /hunter AA BB"
    usage: "/hunter [playername..]"
    permission: "rfm.commands.hunter"
    permission-message: "§c你没有权限执行此命令。"
  runner:
    description: "成为逃走队员。当 playername 参数存在时，则强制让 <playername> 玩家成为逃走队员。playername 可以为多个，例如 /runner AA BB"
    usage: "/runner [playername..]"
    permission: "rfm.commands.runner"
    permission-message: "§c你没有权限执行此命令。"
  leaveteam:
    description: "离开所在队伍。当 playername 参数存在时，则强制让 <playername> 玩家离开其所在队伍。playername 可以为多个，例如 /leaveteam AA BB"
    usage: "/leaveteam [playername..]"
    permission: "rfm.commands.leaveteam"
    permission-message: "§c你没有权限执行此命令。"
    aliases: lt
  endroom:
    description: "设置位于 worldName 世界的 x y z 坐标为终止间位置。若 x y z 未提供且执行者是玩家，则设置执行者的位置为终止间位置。"
    usage: "/endroom [x: int] [y: int] [z: int] [worldName]"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.endroom"
    aliases: erl
  newgroup:
    description: "新建名为 <name> 的猎人组。"
    usage: "/newgroup <name>"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.newgroup"
    aliases: ng
  removegroup:
    description: "移除 <name> 猎人组。"
    usage: "/removegroup <name>"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.removegroup"
    aliases: rg
  activategroup:
    description: "启用在 <name> 组内的所有猎人。"
    usage: "/activategroup <name>"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.activategroup"
    aliases: ag
  deactivategroup:
    description: "禁用在 <name> 组内的所有猎人。"
    usage: "/deactivategroup <name>"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.deactivategroup"
    aliases: dg
  joingroup:
    description: "成为 <name> 组的一具猎人。当 playername 参数存在时，将强制把 <playername> 玩家放入 <name> 组，但前提是该玩家需要是猎人。playername 可以为多个，例如 /jg AA BB"
    usage: "/joingroup <name> [playername..]"
    permission: "rfm.commands.joingroup"
    permission-message: "§c你没有权限执行此命令。"
    aliases: jg
  leavegroup:
    description: "从所在的组离开。当 playername 参数存在时，将强制使 <playername> 玩家离开其所在的组（不是队伍），但前提是该玩家需要是猎人。playername 可以为多个，例如 /lg AA BB"
    usage: "/leavegroup [playername..]"
    permission: "rfm.commands.leavegroup"
    permission-message: "§c你没有权限执行此命令。"
    aliases: lg
  activatehunter:
    description: "启用猎人 <playername> 。当 x y z 提供时则将该猎人放置到提供的位置（适用于重复利用已禁用猎人的时候）。"
    usage: "/activatehunter <playername> [x: int] [y: int] [z: int]"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.activatehunter"
    aliases: ah
  deactivatehunter:
    description: "禁用猎人 <playername> 。"
    usage: "/deactivatehunter <playername>"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.deactivatehunter"
    aliases: dh
  rfmitem:
    description: "获取本插件的一些游戏内道具。此命令属于配置工具，仅管理员可用。"
    usage: "/rfmitem <itemname>"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.rfmitem"
    aliases: ri
  grouplist:
    description: "列出所有已创建的组。"
    usage: "/grouplist"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.grouplist"
    aliases: gl
  teamlist:
    description: "列出两队伍中所有玩家的名字。"
    usage: "/teamlist"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.teamlist"
    aliases: tl
  coinlist:
    description: "列出所有玩家的B币数量。"
    usage: "/coinlist"
    permission: "rfm.commands.coinlist"
    permission-message: "§c你没有权限执行此命令。"
    aliases: cl
  exportcoinlist:
    description: "导出现在的 B币榜 数据到一个文件。"
    usage: "/exportcoinlist"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.exportcoinlist"
    aliases: ecl
  rfmrespawn:
    description: "使 <playerName> 重新加入逃走中游戏。可以批量处理。"
    usage: "/rfmrespawn <playerName..>"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.rfmrespawn"
  rfmsettingsquery:
    description: "查询现有的逃走中游戏配置。"
    usage: "/rfmsettingsquery"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.rfmsettingsquery"
    aliases: rsq
  forcestart:
    description: "(开发者用的调试命令! 请勿使用!) 强制启动一次游戏。"
    usage: "/forcestart"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.forcestart"
  rfmtimer:
    description: "启用/禁用 剩余时间的显示。"
    usage: "/rfmtimer"
    permission: "rfm.commands.rfmtimer"
    permission-message: "§c你没有权限执行此命令。"
  forceresume:
    description: "(开发者用的调试命令! 请勿使用!) 强制使游戏进程继续。"
    usage: "/forceresume"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.forceresume"
  rfmreload:
    description: "重新从硬盘加载配置。但玩家不会从所在的队伍或组离开。"
    usage: "/rfmreload"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.rfmreload"
  playerremaining:
    description: "查看存活和被淘汰的逃走队员列表。"
    usage: "/playerremaining"
    permission-message: "§c你没有权限执行此命令。"
    permission: "rfm.commands.playerremaining"
    aliases: prc

# Permissions
permissions:

  rfm.commands.hunter:
    description: "This permission make players can be hunters."
    default: true

  rfm.commands.runner:
    description: "This permission make players can be runners."
    default: true

  rfm.commands.leaveteam:
    description: "This permission make players can leave their team."
    default: true

  rfm.commands.start:
    description: "This permission make players can start the \"Run For Money\" game."
    default: op

  rfm.commands.forcestart:
    description: "This permission make the administrator can start the \"Run For Money\" game by force."
    default: op

  rfm.commands.forcestop:
    description: "This permission make the administrator can stop the \"Run For Money\" game by force."
    default: op

  rfm.commands.pause:
    description: "This permission make the administrator can pause the \"Run For Money\" game."
    default: op

  rfm.commands.resume:
    description: "This permission make the administrator can resume the \"Run For Money\" game."
    default: op

  rfm.commands.forceresume:
    description: "This permission make the administrator can resume the \"Run For Money\" game by force."
    default: op

  rfm.commands.endroom:
    description: "This permission make the administrator can define the location of endroom."
    default: op

  rfm.commands.newgroup:
    description: "This permission make the administrator can create a new group."
    default: op

  rfm.commands.removegroup:
    description: "This permission make the administrator can remove a group."
    default: op

  rfm.commands.activategroup:
    description: "This permission make the administrator can activate a group."
    default: op

  rfm.commands.deactivategroup:
    description: "This permission make the administrator can deactivate a group."
    default: op
  
  rfm.commands.joingroup:
    description: "This permission make the hunter can join a group."
    default: true
  
  rfm.commands.leavegroup:
    description: "This permission make the hunter can leave their group."
    default: true

  rfm.commands.activatehunter:
    description: "This permission make the administrator can activate a hunter."
    default: op

  rfm.commands.deactivatehunter:
    description: "This permission make the administrator can deactivate a hunter."
    default: op

  rfm.commands.rfmitem:
    description: "This permission make the administrator can get a custom item that registered in ItemRegistry."
    default: op

  rfm.commands.teamlist:
    description: "This permission make the administrator can see the players in which team."
    default: op

  rfm.commands.exportcoinlist:
    description: "This permission make the administrator can export the coin list into a file."
    default: op

  rfm.commands.coinlist:
    description: "This permission make the players can see the coin list."
    default: true

  rfm.commands.rfmrespawn:
    description: "This permission make the administrator can respawn a player that already exited the \"Run For Money\" game."
    default: op

  rfm.commands.rfmsettingsquery:
    description: "This permission make the administrator can query the settings that can affect the game."
    default: op

  rfm.commands.rfmreload:
    description: "This permission make the administrator can reload the configuration files from the disk."
    default: op

  rfm.commands.rfmtimer:
    description: "This permission make the players can decide whether they want to see the game time."
    default: true

  rfm.commands.grouplist:
    description: "This permission makes administrators can see the list of all groups."
    default: op

  rfm.commands.playerremaining:
    description: "This permission make the players can see the remaining player list."
    default: true